-- Switch to prev/next tab in topmost tabbed layout
local i3 = require("i3ipc")
i3.main(function(ipc)
  ipc:on("shutdown", function(ipc)
    print("Shutdown!")
  end)
  ipc:on("window", function(ipc, event)
    print("window event", event.container.id)
    ipc:command(("exec notify-send Window '%s'"):format(event.container.name))
  end)
end)
